FROM python:3.8.2-slim-buster
WORKDIR /youtube_app
COPY . /youtube_app
RUN pip install -r requirements.txt
ENV API_KEY="AIzaSyCUxMiitzSTQhal-znPdoa8DR6cNp6Xk_w"

COPY . .
EXPOSE 5000
ENV FLASK_APP=server.py
CMD ["flask", "run", "--host", "0.0.0.0"]
# COPY . /app

# WORKDIR /app

# RUN python3 -m pip install -r requirements.txt

# ENV API_KEY="AIzaSyCUxMiitzSTQhal-znPdoa8DR6cNp6Xk_w"

# EXPOSE 80

# CMD ["python", "server.py", "0.0.0.0:8000"]

